### ISSUE TITLE
Travis build error

### ISSUE THREAD

**Issue by di-shi** [TransNexus/NexOSS#321] opened 2016-12-12 13:58 UTC
https://travis-ci.org/TransNexus/NexOSS-Web-Server/builds/183250047

Should we increase the timeout? This issue happened several times recently.

**Comment by fenichelar** [comment] 2016-12-12 14:32
I don't know if it will help, I think the issue is before that.

`Trying to start server on port 1337 but can't...Something else is probably running on that port!
Please disable the other server, or choose a different port and try again.`

The tests then timeout because Sails is not running.

**Comment by fenichelar** [comment] 2016-12-12 14:40
I updated the test to not reach time timeout on failure. Let's see what happens.

**Comment by fenichelar** [comment] 2016-12-12 14:46
That didn't help. I increased the timeout as you suggested and it might have fixed it. I'll close this for now and if it happens again we will reopen.

**Closed by fenichelar** 2016-12-12 14:46 UTC
