### ISSUE TITLE
Error Generating SDReporter

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#183] opened 2016-08-21 20:29 UTC
Alec,

I tried to generate a new SDReporter.  I uploaded the attached SDReporter.txt config to .101 and the following errors were returned.  Any ideas?

[SDReporter.txt](https://github.com/TransNexus/NexOSS/files/429082/SDReporter.txt)

$ git status
# On branch master
nothing to commit (working directory clean)

$ undefined
undefined
$ npm run validatePages -- SDReporter
undefined:46
"columns.201.default
": "
"
 ^
SyntaxError: Unexpected token c
    at Object.parse (native)
    at /home/tnr/dev/src/ui2/build/NexOSS-Web-Server/scripts/validatePages.js:71:35
    at /home/tnr/dev/src/ui2/build/NexOSS-Web-Server/node_modules/node-dir/lib/readfiles.js:110:34
    at fs.js:334:14
    at FSReqWrap.oncomplete (fs.js:95:15)

npm ERR! Linux 2.6.32-220.el6.x86_64
npm ERR! argv "/home/tnr/dev/src/ui2/build/local-node/bin/node" "/home/tnr/dev/src/ui2/build/local-node/bin/npm" "run" "validatePages" "--" "SDReporter"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! NexOSS-Web-Server@0.0.0 validatePages: `node ./scripts/validatePages.js "SDReporter"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the NexOSS-Web-Server@0.0.0 validatePages script 'node ./scripts/validatePages.js "SDReporter"'.
npm ERR! This is most likely a problem with the NexOSS-Web-Server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/validatePages.js "SDReporter"
npm ERR! You can get their info via:
npm ERR!     npm owner ls NexOSS-Web-Server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tnr/dev/src/ui2/build/NexOSS-Web-Server/npm-debug.log

**Comment by fenichelar** [comment] 2016-08-22 14:51
Caused by DOS line breaks. Resolved by running `dos2unix`.

**Closed by fenichelar** 2016-08-22 14:51 UTC
