### ISSUE TITLE
SIP Analytics Triggers are not activated

### ISSUE THREAD

**Issue by JimDalton** [TransNexus/NexOSS#289] opened 2016-11-14 22:08 UTC
#### Page Path
/ui/Fraud-Control_SIP-Analytics-Basic_By-Customer-Device_Traffic-Pumping_Trigger-Events

#### Description of Issue
Fraud scores in trigger report exceed Fraud trigger threshold, but no trigger is activated.  No event logged.

**Comment by DmitryIsakbayev** [comment] 2016-11-15 14:10
Looks like a Regression Bug (introduced in 8.16.0).  Should be fixed in 8.16.4

**Comment by DmitryIsakbayev** [comment] 2016-11-15 20:32
The lab has been upgraded to 8.16.4 and trigger events are being generated.

**Closed by DmitryIsakbayev** 2016-11-15 20:32 UTC
